# Generated by Django 5.2.14 on 2026-06-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumo', '0002_producto_activo_alter_consumorealinsumo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
